[tool.poetry]
name = "class-factory"
version = "0.1.0"
description = "class prep products with langchain"
authors = ["speters9 <speters9@stanford.edu>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pandas = "^2.2.2"
scikit-learn = "^1.4.2"
arrow = "^1.3.0"
numpy = "^1.26.4"
python-dotenv = "^1.0.1"
transformers = "^4.40.1"
langchainhub = "^0.1.15"
langchain = "^0.2.9"
langchain-community = "^0.2.7"
sentence-transformers = "^3.0.1"
langchain-huggingface = "^0.0.3"
openai = "^1.37.0"
langchain-openai = "^0.1.17"
torch = { version = "2.0.0", source="torch"}
torchvision = { version = "0.15.1", source="torch"}
torchaudio = { version = "2.0.1", source="torch"}
python-docx = "^1.1.2"
pytesseract = "^0.3.10"
pdf2image = "^1.17.0"
pillow = "^10.4.0"
pymupdf = "^1.24.9"
tiktoken = "^0.7.0"
pyprojroot = "^0.3.0"
spacy = "3.8.0"
contextualspellcheck = "^0.4.4"
img2table = "^1.3.0"
selenium = "^4.24.0"
bs4 = "^0.0.2"
plogging = "^0.0.1"
python-pptx = "^1.0.2"
openpyxl = "^3.1.5"
pre-commit = "^3.8.0"
autopep8 = "2.0.4"
streamlit = "^1.38.0"
gradio = "^4.44.0"
wordcloud = "^1.9.3"
pyvis = "^0.3.2"
jedi = "0.18.2"
html2text = "^2024.2.26"
reportlab = "^4.2.5"
cookiecutter-data-science = "^2.0.0"
cdlib = "^0.4.0"
leidenalg = "^0.10.2"
pytest = "^8.3.3"
pdf2docx = "^0.5.8"
iprogress = "^0.4"
ipywidgets = "^8.1.5"
inflect = "^7.4.0"
pypdf = "^5.0.1"
qrcode = {extras = ["pi"], version = "^8.0"}
responses = "^0.25.3"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu118"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
